# Generated by Django 5.1.4 on 2026-07-04 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('num_trabajadores', models.PositiveIntegerField()),
                ('nivel_riesgo', models.PositiveSmallIntegerField()),
                ('capitulo_vigente', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('suspendida', 'Suspendida')], default='pendiente', max_length=20)),
                ('representante_legal', models.CharField(blank=True, max_length=255)),
                ('arl', models.CharField(blank=True, max_length=100)),
                ('sector_economico', models.CharField(blank=True, max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
    ]
