# Generated by Django 5.1.4 on 2026-07-20 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciiu_768_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciiu_768_principal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciiu_768_secundarios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciiu_codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciiu_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditorEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('auditor', models.ForeignKey(db_column='auditor_id', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='auditores', to='empresas.empresa')),
            ],
            options={
                'db_table': 'auditores_empresas',
            },
        ),
        migrations.CreateModel(
            name='SolicitudEliminacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=100)),
                ('registro_id', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobador', models.ForeignKey(blank=True, db_column='aprobador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_eliminacion', to='empresas.empresa')),
                ('solicitante', models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_eliminacion',
            },
        ),
    ]
