# Generated by Django 6.1 on 2026-09-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_ciiu_768_metadata_empresa_ciiu_768_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
