# Generated by Django 6.1 on 2026-09-27 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_logo_url'),
        ('estandares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransicionCapitulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capitulo_anterior', models.CharField(max_length=10)),
                ('capitulo_nuevo', models.CharField(max_length=10)),
                ('motivo', models.TextField(blank=True, default='')),
                ('contexto_anterior', models.JSONField(default=dict)),
                ('contexto_nuevo', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_capitulo', to='empresas.empresa')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transiciones', to='estandares.evaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transiciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transiciones_capitulo',
                'ordering': ['-created_at'],
            },
        ),
    ]
