# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('estandares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('no_conformidad', 'No conformidad'), ('observacion', 'Observación'), ('oportunidad_mejora', 'Oportunidad de mejora')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='estandares.evaluacion')),
            ],
            options={
                'db_table': 'hallazgos',
            },
        ),
        migrations.CreateModel(
            name='PlanMejora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('prioridad', models.CharField(choices=[('urgente', 'Urgente (3 meses)'), ('importante', 'Importante (6 meses)'), ('aceptable', 'Aceptable (1 año)')], max_length=20)),
                ('fecha_limite', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mejora', to='empresas.empresa')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_mejora', to='estandares.evaluacion')),
            ],
            options={
                'db_table': 'plan_mejora',
            },
        ),
    ]
