# Generated by Django 6.1 on 2026-09-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandares', '0002_alter_apelacion_estado'),
        ('hallazgos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='estandar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='estandares.estandar'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='estandares.respuesta'),
        ),
    ]
