# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_usuarios', models.IntegerField()),
                ('max_evidencias_mb', models.IntegerField()),
                ('tiene_auditoria', models.BooleanField(default=False)),
                ('tiene_informes', models.BooleanField(default=False)),
                ('tiene_calendario', models.BooleanField(default=False)),
                ('tiene_alertas_email', models.BooleanField(default=False)),
                ('tiene_historico', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='empresas.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='planes.plan')),
            ],
            options={
                'db_table': 'suscripciones',
            },
        ),
    ]
