# Generated by Django 5.1.4 on 2026-07-06 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfiliacionTrabajador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('eps', 'EPS'), ('arl', 'ARL'), ('pension', 'Pensión'), ('caja', 'Caja de compensación')], max_length=20)),
                ('entidad_nombre', models.CharField(max_length=150)),
                ('numero_afiliacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_afiliacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'afiliaciones_trabajador',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=200)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField()),
                ('num_asistentes', models.IntegerField(default=0)),
                ('tiene_certificado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCapacitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asistio', models.BooleanField(default=False)),
                ('certificado_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participantes_capacitacion',
            },
        ),
        migrations.CreateModel(
            name='PlanillaSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('tipo_carga', models.CharField(max_length=20)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_pago', models.CharField(default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'planillas_seguridad_social',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=30)),
                ('tipo_vinculacion', models.CharField(choices=[('dependiente', 'Dependiente'), ('independiente', 'Independiente'), ('contratista', 'Contratista')], max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trabajadores',
            },
        ),
    ]
