# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0001_initial'),
        ('empresas', '0001_initial'),
        ('evidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliaciontrabajador',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afiliaciones', to='evidencias.archivo'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='participantecapacitacion',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='capacitaciones.capacitacion'),
        ),
        migrations.AddField(
            model_name='planillaseguridad',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas', to='evidencias.archivo'),
        ),
        migrations.AddField(
            model_name='planillaseguridad',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='empresas.empresa'),
        ),
    ]
