# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0002_initial'),
        ('organizacion', '0001_initial'),
        ('perfilcargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='perfil_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='organizacion.sede'),
        ),
        migrations.AddField(
            model_name='participantecapacitacion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='capacitaciones.trabajador'),
        ),
        migrations.AddField(
            model_name='afiliaciontrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliaciones', to='capacitaciones.trabajador'),
        ),
        migrations.AddConstraint(
            model_name='trabajador',
            constraint=models.UniqueConstraint(fields=('empresa', 'documento'), name='uq_trabajador_empresa_documento'),
        ),
    ]
