# Generated by Django 6.1 on 2026-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='estado_contractual',
            field=models.CharField(choices=[('activo', 'Activo'), ('periodo_prueba', 'Periodo de prueba'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('incapacidad', 'Incapacidad médica'), ('suspendido', 'Suspendido'), ('retirado', 'Retirado')], default='activo', help_text='Derivado automáticamente de NovedadLaboral con jerarquía de precedencia', max_length=30),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado_operativo',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('restringido', 'Restringido'), ('pendiente_documental', 'Pendiente documental'), ('no_apto', 'No apto')], default='pendiente_documental', help_text='Derivado automáticamente de MICHC', max_length=30),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_fin_periodo_prueba',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_fin_prorroga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_inicio_periodo_prueba',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_inicio_prorroga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='remuneracion_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='remuneracion_tipo',
            field=models.CharField(choices=[('salario', 'Salario'), ('honorarios', 'Honorarios')], default='salario', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tiene_prorroga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('fijo', 'Término fijo'), ('indefinido', 'Término indefinido'), ('obra_labor', 'Por obra o labor'), ('prestacion_servicios', 'Prestación de servicios'), ('aprendizaje', 'Contrato de aprendizaje')], max_length=30, null=True),
        ),
    ]
