# Generated by Django 5.1.4 on 2026-07-20 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_ciiu_768_metadata_empresa_ciiu_768_principal_and_more'),
        ('organizacion', '0002_initial'),
        ('perfilcargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCompetencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cargo_competencias',
            },
        ),
        migrations.CreateModel(
            name='CargoEPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_personalizado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cargo_epps',
            },
        ),
        migrations.CreateModel(
            name='CargoFuncion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cargo_funciones',
            },
        ),
        migrations.CreateModel(
            name='CargoIndicador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('meta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cargo_indicadores',
            },
        ),
        migrations.CreateModel(
            name='CargoPeligro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_personalizado', models.CharField(blank=True, max_length=255, null=True)),
                ('clasificacion_personalizada', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cargo_peligros',
            },
        ),
        migrations.CreateModel(
            name='CargoResponsabilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cargo_responsabilidades',
            },
        ),
        migrations.CreateModel(
            name='CargoVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_version', models.IntegerField()),
                ('snapshot', models.JSONField()),
                ('motivo_cambio', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cargo_versiones',
            },
        ),
        migrations.CreateModel(
            name='CatalogoEPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_epps',
            },
        ),
        migrations.CreateModel(
            name='CatalogoPeligro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_peligros',
            },
        ),
        migrations.AddField(
            model_name='perfilcargo',
            name='nodo_organigrama_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilcargo',
            name='proceso_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='perfilcargo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_perfil_cargo_codigo'),
        ),
        migrations.AddField(
            model_name='cargocompetencia',
            name='perfil_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='cargoepp',
            name='perfil_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epps', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='cargofuncion',
            name='perfil_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='cargoindicador',
            name='perfil_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='cargopeligro',
            name='perfil_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peligros', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='cargoresponsabilidad',
            name='perfil_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='cargoversion',
            name='perfil_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='cargoepp',
            name='catalogo_epp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfilcargo.catalogoepp'),
        ),
        migrations.AddField(
            model_name='catalogopeligro',
            name='epps_sugeridos',
            field=models.ManyToManyField(db_table='catalogo_peligro_epps', to='perfilcargo.catalogoepp'),
        ),
        migrations.AddField(
            model_name='cargopeligro',
            name='catalogo_peligro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfilcargo.catalogopeligro'),
        ),
    ]
