# Generated by Django 6.1 on 2026-09-27 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilcargo', '0003_perfilcargo_fase1_extendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcargo',
            name='cargo_critico',
            field=models.BooleanField(default=False, help_text='Indicador binario de criticidad simple. Se evalúa automáticamente si realiza tareas críticas o hay mayor riesgo.'),
        ),
        migrations.AddField(
            model_name='perfilcargo',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, help_text='Dependencia jerárquica asociada directamente a un perfil de cargo, no a persona (§1.1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados_directos', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='perfilcargo',
            name='tipo_cargo',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('operativo', 'Operativo'), ('apoyo', 'De Apoyo'), ('otro', 'Otros de acuerdo al mapa de procesos')], default='operativo', help_text='Clasificación del tipo de cargo según el mapa de procesos (§1.1)', max_length=30),
        ),
    ]
