# Generated by Django 6.1 on 2026-08-22 13:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0004_trabajador_estado_contractual_and_more'),
        ('evidencias', '0001_initial'),
        ('perfilcargo', '0003_perfilcargo_fase1_extendido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionCompetencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_alcanzado', models.IntegerField(help_text='Nivel alcanzado (1: Básico, 2: Intermedio, 3: Avanzado, 4: Experto)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('brecha_calculada', models.IntegerField(default=0, help_text='Brecha negativa (Nivel Requerido - Nivel Alcanzado). 0 si cumple o supera.')),
                ('fecha_evaluacion', models.DateField()),
                ('metodo', models.CharField(choices=[('observacion_directa', 'Observación Directa en Puesto'), ('prueba_tecnica', 'Prueba Técnica / Conocimiento'), ('evaluacion_360', 'Evaluación 360° / Jefe Directo'), ('certificacion', 'Certificación / Título Acreditado'), ('entrevista', 'Entrevista por Competencias'), ('autoevaluacion', 'Autoevaluación')], default='evaluacion_360', max_length=40)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='perfilcargo.cargocompetencia')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_evaluadas', to=settings.AUTH_USER_MODEL)),
                ('soporte_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_competencias', to='evidencias.archivo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_competencias', to='capacitaciones.trabajador')),
            ],
            options={
                'db_table': 'evaluaciones_competencias_mcc',
                'ordering': ['-fecha_evaluacion', '-created_at'],
                'indexes': [models.Index(fields=['trabajador', 'fecha_evaluacion'], name='evaluacione_trabaja_8cd670_idx'), models.Index(fields=['cargo_competencia', 'nivel_alcanzado'], name='evaluacione_cargo_c_c05434_idx')],
            },
        ),
    ]
