# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('estrategico', 'Estratégico'), ('misional', 'Misional'), ('apoyo', 'Apoyo')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'procesos',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='NodoOrganigrama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('nivel', models.IntegerField()),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organigrama', to='empresas.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='organizacion.nodoorganigrama')),
            ],
            options={
                'db_table': 'nodos_organigrama',
                'ordering': ['nivel', 'orden'],
            },
        ),
    ]
