# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('perfilcargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodoorganigrama',
            name='perfil_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos_organigrama', to='perfilcargo.perfilcargo'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subprocesos', to='organizacion.proceso'),
        ),
        migrations.AddField(
            model_name='sede',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='empresas.empresa'),
        ),
    ]
