from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.estandares.models import Estandar


ESTANDARES_DATA = [
    # ─── CAPÍTULO I: ≤10 trabajadores, riesgo I, II o III ────────────────
    {
        "capitulo": "I",
        "ciclo_phva": "Planear",
        "codigo": "I-1",
        "nombre": "Asignación de persona que diseña el Sistema de Gestión de SST",
        "descripcion": "Asignar una persona que cumpla con el perfil requerido para diseñar el SG-SST según la normatividad vigente.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "I",
        "ciclo_phva": "Planear",
        "codigo": "I-2",
        "nombre": "Afiliación al Sistema de Seguridad Social Integral",
        "descripcion": "Afiliación a los Sistemas de Seguridad Social en Salud, Pensión y Riesgos Laborales de acuerdo con la normatividad vigente.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "I",
        "ciclo_phva": "Hacer",
        "codigo": "I-3",
        "nombre": "Capacitación en SST",
        "descripcion": "Elaborar y ejecutar programa o actividades de capacitación en promoción y prevención, que incluya los peligros/riesgos prioritarios y las medidas de prevención y control.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "I",
        "ciclo_phva": "Planear",
        "codigo": "I-4",
        "nombre": "Plan Anual de Trabajo",
        "descripcion": "Elaborar el Plan Anual de Trabajo del SG-SST firmado por el empleador, identificando objetivos, metas, responsabilidades, recursos y cronograma anual.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "I",
        "ciclo_phva": "Hacer",
        "codigo": "I-5",
        "nombre": "Evaluaciones médicas ocupacionales",
        "descripcion": "Realizar las evaluaciones médicas ocupacionales de acuerdo con la normatividad y los peligros/riesgos a los cuales se encuentre expuesto el trabajador.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "I",
        "ciclo_phva": "Planear",
        "codigo": "I-6",
        "nombre": "Identificación de peligros; evaluación y valoración de riesgos",
        "descripcion": "Realizar la identificación de peligros y la evaluación y valoración de los riesgos con el acompañamiento de la ARL.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "I",
        "ciclo_phva": "Hacer",
        "codigo": "I-7",
        "nombre": "Medidas de prevención y control frente a peligros/riesgos identificados",
        "descripcion": "Ejecutar las actividades de prevención y control de peligros y/o riesgos, con base en el resultado de la identificación de peligros, la evaluación y valoración de los riesgos.",
        "puntaje_maximo": Decimal("2.5"),
    },

    # ─── CAPÍTULO II: 11-50 trabajadores, riesgo I, II o III ─────────────
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.1",
        "nombre": "Responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST",
        "descripcion": "Asignación y documentación del responsable del SG-SST.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.2",
        "nombre": "Responsabilidades en el Sistema de Gestión de Seguridad y Salud en el Trabajo – SG-SST",
        "descripcion": "Definición y documentación de responsabilidades en el SG-SST.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.3",
        "nombre": "Asignación de recursos para el Sistema de Gestión en Seguridad y Salud en el Trabajo",
        "descripcion": "Asignación de recursos económicos, técnicos y humanos para el desarrollo del SG-SST.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.4",
        "nombre": "Afiliación al Sistema General de Riesgos Laborales",
        "descripcion": "Garantizar la afiliación de todos los trabajadores al Sistema General de Riesgos Laborales.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.5",
        "nombre": "Identificación de trabajadores de alto riesgo y cotización de pensión especial",
        "descripcion": "Identificar trabajadores en actividades de alto riesgo y garantizar la cotización especial de pensión cuando aplique.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.6",
        "nombre": "Conformación COPASST",
        "descripcion": "Conformar, capacitar y verificar el funcionamiento del COPASST.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.7",
        "nombre": "Capacitación COPASST",
        "descripcion": "Capacitar a los integrantes del COPASST para el cumplimiento efectivo de sus responsabilidades.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.1.8",
        "nombre": "Conformación Comité de Convivencia",
        "descripcion": "Conformar y garantizar el funcionamiento del Comité de Convivencia Laboral.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.2.1",
        "nombre": "Programa de Capacitación Promoción y Prevención PYP",
        "descripcion": "Elaborar y ejecutar el programa de capacitación anual en promoción y prevención.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.2.2",
        "nombre": "Inducción y Reinducción en Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST, actividades de Promoción y Prevención PyP",
        "descripcion": "Realizar actividades de inducción y reinducción en SST a todos los trabajadores.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-1.2.3",
        "nombre": "Responsables del Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST con curso virtual de 50 horas",
        "descripcion": "El responsable del SG-SST debe contar con el curso virtual de capacitación de 50 horas definido por el Ministerio del Trabajo.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.1.1",
        "nombre": "Política de Seguridad y Salud en el Trabajo",
        "descripcion": "Elaborar política de SST escrita, firmada, fechada y comunicada al COPASST y a todos los trabajadores.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.2.1",
        "nombre": "Objetivos definidos, claros, medibles, cuantificables, con metas, documentados, revisados del SG-SST",
        "descripcion": "Definir los objetivos del SG-SST con metas claras, medibles y cuantificables.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.3.1",
        "nombre": "Evaluación e identificación de prioridades",
        "descripcion": "Realizar la evaluación inicial del SG-SST identificando las prioridades para el plan de trabajo.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.4.1",
        "nombre": "Plan que identifica objetivos, metas, responsabilidades, recursos con cronograma y firmado",
        "descripcion": "Diseñar el Plan Anual de Trabajo para el cumplimiento del SG-SST.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.5.1",
        "nombre": "Archivo o retención documental del Sistema de Gestión en Seguridad y Salud en el Trabajo SG-SST",
        "descripcion": "Mantener el archivo de los documentos del SG-SST por el término establecido en la normatividad.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.6.1",
        "nombre": "Rendición sobre el desempeño",
        "descripcion": "Realizar anualmente la Rendición de Cuentas del desarrollo del SG-SST.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.7.1",
        "nombre": "Matriz legal",
        "descripcion": "Definir la matriz legal que contemple las normas actualizadas del Sistema General de Riesgos Laborales aplicables a la empresa.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.8.1",
        "nombre": "Mecanismos de comunicación, auto reporte en Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST",
        "descripcion": "Disponer de mecanismos eficaces para recibir y responder las comunicaciones internas y externas relativas a SST.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.9.1",
        "nombre": "Identificación, evaluación para adquisición de productos y servicios en Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST",
        "descripcion": "Establecer un procedimiento para la identificación y evaluación de las especificaciones en SST de las compras y adquisición de productos y servicios.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.10.1",
        "nombre": "Evaluación y selección de proveedores y contratistas",
        "descripcion": "Establecer los aspectos de SST para la evaluación y selección de proveedores y contratistas.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Planear",
        "codigo": "II-2.11.1",
        "nombre": "Evaluación del impacto de cambios internos y externos en el Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST",
        "descripcion": "Disponer de un procedimiento para evaluar el impacto sobre SST de los cambios internos o externos.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.1",
        "nombre": "Descripción sociodemográfica y Diagnóstico de Condiciones de Salud",
        "descripcion": "Identificar las características de la población trabajadora y el diagnóstico de condiciones de salud.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.2",
        "nombre": "Actividades de Medicina del Trabajo y de Prevención y Promoción de la Salud",
        "descripcion": "Desarrollar las actividades de medicina del trabajo, prevención y promoción de la salud.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.3",
        "nombre": "Información al médico de los perfiles de cargo",
        "descripcion": "Informar al médico que realiza las evaluaciones ocupacionales los perfiles de cargos.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.4",
        "nombre": "Realización de Evaluaciones Médicas Ocupacionales: Peligros- Periodicidad/Comunicación al Trabajador",
        "descripcion": "Realizar las evaluaciones médicas ocupacionales según normatividad y peligros/riesgos.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.5",
        "nombre": "Custodia de Historias Clínicas",
        "descripcion": "Tener la custodia de las historias clínicas a cargo de una institución prestadora de servicios en SST.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.6",
        "nombre": "Restricciones y recomendaciones médico laborales",
        "descripcion": "Cumplir las restricciones y recomendaciones médico laborales realizadas por la EPS o ARL.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.7",
        "nombre": "Estilos de vida y entornos saludables (Tabaquismo, alcoholismo, farmacodependencia y obesidad)",
        "descripcion": "Elaborar y ejecutar un programa para promover estilos de vida y entornos de trabajo saludables.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.8",
        "nombre": "Agua potable, servicios sanitarios y disposición de basuras",
        "descripcion": "Contar con suministro permanente de agua potable, servicios sanitarios y mecanismos para disponer excretas y basuras.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.1.9",
        "nombre": "Eliminación adecuada de residuos sólidos, líquidos o gaseosos",
        "descripcion": "Eliminar los residuos sólidos, líquidos o gaseosos de forma que no se ponga en riesgo a los trabajadores.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.2.1",
        "nombre": "Reporte de los accidentes de trabajo y enfermedad laboral a la ARL, EPS y Dirección Territorial del Ministerio",
        "descripcion": "Reportar a la ARL y EPS todos los accidentes de trabajo y enfermedades laborales diagnosticadas.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.2.2",
        "nombre": "Investigación de Accidentes, Incidentes y Enfermedad Laboral",
        "descripcion": "Investigar los incidentes y todos los accidentes de trabajo y las enfermedades cuando sean diagnosticadas como laborales, con participación del COPASST.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.2.3",
        "nombre": "Registro y análisis estadístico de Incidentes, Accidentes de Trabajo y Enfermedad Laboral",
        "descripcion": "Llevar registro estadístico de los accidentes de trabajo y enfermedades laborales.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.3.1",
        "nombre": "Medición de la frecuencia de la accidentalidad",
        "descripcion": "Medir la frecuencia de los accidentes como mínimo una vez al mes.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.3.2",
        "nombre": "Medición de la severidad de la accidentalidad",
        "descripcion": "Medir la severidad de los accidentes de trabajo como mínimo una vez al mes.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.3.3",
        "nombre": "Medición de la mortalidad por Accidentes de Trabajo",
        "descripcion": "Medir la mortalidad por accidentes como mínimo una vez al año.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.3.4",
        "nombre": "Medición de la prevalencia de Enfermedad Laboral",
        "descripcion": "Medir la prevalencia de la enfermedad laboral como mínimo una vez al año.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.3.5",
        "nombre": "Medición de la incidencia de Enfermedad Laboral",
        "descripcion": "Medir la incidencia de la enfermedad laboral como mínimo una vez al año.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-3.3.6",
        "nombre": "Medición del ausentismo por causa médica",
        "descripcion": "Medir el ausentismo por incapacidad de origen laboral y común como mínimo una vez al mes.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.1.1",
        "nombre": "Metodología para la identificación de peligros, evaluación y valoración de los Riesgos",
        "descripcion": "Definir y aplicar una metodología para la identificación de peligros y evaluación de riesgos.",
        "puntaje_maximo": Decimal("4"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.1.2",
        "nombre": "Identificación de peligros con participación de todos los niveles de la empresa",
        "descripcion": "Realizar la identificación de peligros y valoración de riesgos con participación de todos los niveles.",
        "puntaje_maximo": Decimal("4"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.1.3",
        "nombre": "Identificación de sustancias catalogadas como carcinógenas o con toxicidad aguda",
        "descripcion": "Identificar sustancias carcinógenas o con toxicidad aguda y priorizar los riesgos asociados.",
        "puntaje_maximo": Decimal("3"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.1.4",
        "nombre": "Realización mediciones ambientales, químicos, físicos y biológicos",
        "descripcion": "Realizar mediciones ambientales de los riesgos prioritarios provenientes de peligros químicos, físicos y/o biológicos.",
        "puntaje_maximo": Decimal("4"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.2.1",
        "nombre": "Implementación de medidas de prevención y control de peligros",
        "descripcion": "Ejecutar las medidas de prevención y control con base en la identificación de peligros.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.2.2",
        "nombre": "Verificación de aplicación de medidas de prevención y control por parte de los trabajadores",
        "descripcion": "Verificar la aplicación de las medidas de prevención y control por parte de los trabajadores.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.2.3",
        "nombre": "Elaboración de procedimientos, instructivos, fichas, protocolos",
        "descripcion": "Elaborar procedimientos, instructivos y fichas técnicas de seguridad y salud en el trabajo.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.2.4",
        "nombre": "Realización de inspecciones a instalaciones, maquinaria o equipos con participación del COPASST",
        "descripcion": "Elaborar formatos de registro para las visitas de inspección y realizarlas sistemáticamente.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.2.5",
        "nombre": "Mantenimiento periódico de instalaciones, equipos, máquinas, herramientas",
        "descripcion": "Realizar el mantenimiento periódico de instalaciones, equipos, máquinas y herramientas.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-4.2.6",
        "nombre": "Entrega de Elementos de Protección Persona EPP, se verifica con contratistas y subcontratistas",
        "descripcion": "Suministrar los elementos de protección personal y capacitar en su uso adecuado.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-5.1.1",
        "nombre": "Se cuenta con el Plan de Prevención, Preparación y respuesta ante emergencias",
        "descripcion": "Elaborar el plan de prevención, preparación y respuesta ante emergencias.",
        "puntaje_maximo": Decimal("5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Hacer",
        "codigo": "II-5.1.2",
        "nombre": "Brigada de prevención conformada, capacitada y dotada",
        "descripcion": "Conformar, capacitar y dotar la brigada de prevención, preparación y respuesta ante emergencias.",
        "puntaje_maximo": Decimal("5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Verificar",
        "codigo": "II-6.1.1",
        "nombre": "Definición de Indicadores del SG-SST de acuerdo condiciones de la empresa",
        "descripcion": "Definir indicadores que permitan evaluar el SG-SST conforme los indicadores mínimos.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Verificar",
        "codigo": "II-6.1.2",
        "nombre": "La empresa adelanta auditoría por lo menos una vez al año",
        "descripcion": "Realizar una auditoría anual planificada con participación del COPASST.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Verificar",
        "codigo": "II-6.1.3",
        "nombre": "Revisión anual por la alta dirección, resultados y alcance de la auditoría",
        "descripcion": "Revisar como mínimo una vez al año por parte de la alta dirección los resultados del SG-SST.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Verificar",
        "codigo": "II-6.1.4",
        "nombre": "Planificación auditoría con el COPASST",
        "descripcion": "Planificar la auditoría con participación del COPASST.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Actuar",
        "codigo": "II-7.1.1",
        "nombre": "Definición de acciones preventivas y correctivas con base en resultados del SG-SST",
        "descripcion": "Definir e implementar las acciones preventivas y/o correctivas con base en los resultados del SG-SST.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Actuar",
        "codigo": "II-7.1.2",
        "nombre": "Acciones de mejora conforme a revisión de la Alta Dirección",
        "descripcion": "Implementar acciones de mejora conforme a la revisión de la Alta Dirección.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Actuar",
        "codigo": "II-7.1.3",
        "nombre": "Acciones de mejora con base en investigaciones de accidentes de trabajo y enfermedades laborales",
        "descripcion": "Definir e implementar acciones correctivas con base en los resultados de las investigaciones.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "II",
        "ciclo_phva": "Actuar",
        "codigo": "II-7.1.4",
        "nombre": "Elaboración Plan de mejoramiento e implementación de medidas y acciones correctivas solicitadas por autoridades y ARL",
        "descripcion": "Implementar las medidas y acciones correctivas producto de requerimientos de autoridades administrativas y ARL.",
        "puntaje_maximo": Decimal("2.5"),
    },

    # ─── CAPÍTULO III: >50 trabajadores o ≤50 con riesgo IV/V ───────────
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.1",
        "nombre": "Responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST",
        "descripcion": "Asignación del responsable del SG-SST con perfil profesional en SST.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.2",
        "nombre": "Responsabilidades en el Sistema de Gestión de Seguridad y Salud en el Trabajo – SG-SST",
        "descripcion": "Asignar y documentar las responsabilidades específicas en el SG-SST a todos los niveles.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.3",
        "nombre": "Asignación de recursos para el Sistema de Gestión en Seguridad y Salud en el Trabajo",
        "descripcion": "Definir y asignar el talento humano, recursos financieros, técnicos y tecnológicos requeridos.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.4",
        "nombre": "Afiliación al Sistema General de Riesgos Laborales",
        "descripcion": "Garantizar que todos los trabajadores estén afiliados al Sistema de Seguridad Social.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.5",
        "nombre": "Identificación de trabajadores de alto riesgo y cotización de pensión especial",
        "descripcion": "Identificar trabajadores en actividades de alto riesgo y gestionar cotización especial.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.6",
        "nombre": "Conformación y funcionamiento del COPASST",
        "descripcion": "Conformar y garantizar el funcionamiento del COPASST.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.7",
        "nombre": "Capacitación de los integrantes del COPASST",
        "descripcion": "Capacitar a los integrantes del COPASST.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.1.8",
        "nombre": "Conformación y funcionamiento del Comité de Convivencia Laboral",
        "descripcion": "Conformar y garantizar el funcionamiento del Comité de Convivencia Laboral.",
        "puntaje_maximo": Decimal("0.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.2.1",
        "nombre": "Programa de Capacitación Promoción y Prevención PYP",
        "descripcion": "Elaborar y ejecutar el programa de capacitación anual extensivo a todos los niveles.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.2.2",
        "nombre": "Inducción y Reinducción en SG-SST",
        "descripcion": "Realizar actividades de inducción y reinducción previas al inicio de labores.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-1.2.3",
        "nombre": "Responsables del SG-SST con curso virtual de 50 horas",
        "descripcion": "El responsable del SG-SST realiza el curso virtual de 50 horas.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.1.1",
        "nombre": "Política de Seguridad y Salud en el Trabajo",
        "descripcion": "Establecer por escrito la Política de SST, fechada, firmada por el representante legal y comunicada al COPASSST.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.2.1",
        "nombre": "Objetivos del SG-SST",
        "descripcion": "Definir los objetivos del SG-SST con metas claras, medibles y cuantificables.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.3.1",
        "nombre": "Evaluación inicial del Sistema de Gestión de Gestión",
        "descripcion": "Realizar la evaluación inicial del SG-SST identificando prioridades.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.4.1",
        "nombre": "Plan Anual de Trabajo",
        "descripcion": "Diseñar y definir el plan anual de trabajo para el cumplimiento del SG-SST.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.5.1",
        "nombre": "Archivo y retención documental del SG-SST",
        "descripcion": "Contar con un sistema de archivo y retención documental para los registros del SG-SST.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.6.1",
        "nombre": "Rendición de cuentas",
        "descripcion": "Realizar anualmente la Rendición de Cuentas del SG-SST a todos los niveles.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.7.1",
        "nombre": "Matriz legal",
        "descripcion": "Definir la matriz legal con las normas actualizadas del Sistema General de Riesgos Laborales.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.8.1",
        "nombre": "Mecanismos de comunicación",
        "descripcion": "Disponer de mecanismos eficaces para comunicaciones internas y externas relativas a SST.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.9.1",
        "nombre": "Identificación y evaluación para adquisición de bienes y servicios",
        "descripcion": "Establecer procedimiento para identificar y evaluar especificaciones SST en compras.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.10.1",
        "nombre": "Evaluación y selección de proveedores y contratistas",
        "descripcion": "Establecer criterios SST para la evaluación y selección de proveedores.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Planear",
        "codigo": "III-2.11.1",
        "nombre": "Gestión del cambio",
        "descripcion": "Disponer procedimiento para evaluar impacto de cambios internos y externos sobre SST.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.1",
        "nombre": "Descripción sociodemográfica y Diagnóstico de Condiciones de Salud",
        "descripcion": "Recolectar información actualizada de todos los trabajadores del último año.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.2",
        "nombre": "Actividades de medicina del trabajo y de prevención y promoción de la Salud",
        "descripcion": "Desarrollar actividades de medicina del trabajo y programas de vigilancia epidemiológica.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.3",
        "nombre": "Perfiles de cargos",
        "descripcion": "Informar al médico los perfiles de cargos con descripción de tareas y medio laboral.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.4",
        "nombre": "Evaluaciones médicas ocupacionales",
        "descripcion": "Realizar evaluaciones médicas ocupacionales con la periodicidad requerida.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.5",
        "nombre": "Custodia de Historias Clínicas",
        "descripcion": "Garantizar la custodia de historias clínicas a cargo de institución prestadora de SST.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.6",
        "nombre": "Restricciones y recomendaciones médico laborales",
        "descripcion": "Cumplir recomendaciones y restricciones médico laborales de EPS y ARL.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.7",
        "nombre": "Estilos de vida y entorno saludable",
        "descripcion": "Elaborar y ejecutar programa para promover estilos de vida saludables.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.8",
        "nombre": "Servicios de higiene",
        "descripcion": "Contar con suministro permanente de agua potable, servicios sanitarios y disposición de basuras.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.1.9",
        "nombre": "Manejo de Residuos",
        "descripcion": "Eliminar los residuos sólidos, líquidos o gaseosos de forma que no se ponga en riesgo a los trabajadores.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.2.1",
        "nombre": "Reporte de accidentes de trabajo y enfermedades laborales",
        "descripcion": "Reportar a ARL, EPS y Dirección Territorial del Ministerio los accidentes y enfermedades laborales.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.2.2",
        "nombre": "Investigación de incidentes, accidentes de trabajo y enfermedades laborales",
        "descripcion": "Investigar incidentes y accidentes con participación del COPASST.",
        "puntaje_maximo": Decimal("2"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.2.3",
        "nombre": "Registro y análisis estadístico de accidentes y enfermedades laborales",
        "descripcion": "Llevar y analizar el registro estadístico de accidentes y enfermedades laborales.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.3.1",
        "nombre": "Medición de la frecuencia de la accidentalidad",
        "descripcion": "Medir frecuencia de accidentes mensualmente con clasificación del origen del peligro.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.3.2",
        "nombre": "Medición de la severidad de la accidentalidad",
        "descripcion": "Medir severidad de accidentes mensualmente.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.3.3",
        "nombre": "Medición de la mortalidad por Accidentes de Trabajo",
        "descripcion": "Medir mortalidad por accidentes mínimo una vez al año.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.3.4",
        "nombre": "Medición de la prevalencia de Enfermedad Laboral",
        "descripcion": "Medir prevalencia de enfermedad laboral mínimo una vez al año.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.3.5",
        "nombre": "Medición de la incidencia de Enfermedad Laboral",
        "descripcion": "Medir incidencia de enfermedad laboral mínimo una vez al año.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-3.3.6",
        "nombre": "Medición del ausentismo por causa médica",
        "descripcion": "Medir ausentismo por incapacidad laboral y común mínimo una vez al mes.",
        "puntaje_maximo": Decimal("1"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.1.1",
        "nombre": "Metodología para la identificación de peligros, evaluación y valoración de los Riesgos",
        "descripcion": "Definir y aplicar metodología para identificación de peligros con alcance en todos los centros de trabajo.",
        "puntaje_maximo": Decimal("4"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.1.2",
        "nombre": "Identificación de peligros con participación de todos los niveles de la empresa",
        "descripcion": "Realizar identificación con participación de todos los trabajadores y actualizarla mínimo una vez al año.",
        "puntaje_maximo": Decimal("4"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.1.3",
        "nombre": "Identificación de sustancias catalogadas como carcinógenas o con toxicidad aguda",
        "descripcion": "Identificar y priorizar riesgos de sustancias carcinógenas o con toxicidad aguda.",
        "puntaje_maximo": Decimal("3"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.1.4",
        "nombre": "Realización mediciones ambientales, químicos, físicos y biológicos",
        "descripcion": "Realizar mediciones ambientales de riesgos prioritarios.",
        "puntaje_maximo": Decimal("4"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.2.1",
        "nombre": "Implementación de medidas de prevención y control de peligros",
        "descripcion": "Ejecutar medidas de prevención y control basadas en la identificación de peligros.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.2.2",
        "nombre": "Verificación de aplicación de medidas de prevención y control",
        "descripcion": "Verificar la aplicación de medidas de prevención por parte de los trabajadores.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.2.3",
        "nombre": "Elaboración de procedimientos, instructivos, fichas, protocolos",
        "descripcion": "Elaborar procedimientos e instructivos de seguridad y salud en el trabajo.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.2.4",
        "nombre": "Realización de inspecciones a instalaciones, maquinaria o equipos con participación del COPASST",
        "descripcion": "Realizar inspecciones sistemáticas a instalaciones, maquinaria y equipos.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.2.5",
        "nombre": "Mantenimiento periódico de instalaciones, equipos, máquinas y herramientas",
        "descripcion": "Realizar mantenimiento periódico de acuerdo con manuales y fichas técnicas.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-4.2.6",
        "nombre": "Entrega de EPP y capacitación en uso adecuado",
        "descripcion": "Suministrar EPP oportunamente y capacitar en su uso adecuado.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-5.1.1",
        "nombre": "Plan de Prevención, Preparación y respuesta ante emergencias",
        "descripcion": "Elaborar plan de emergencias que identifique amenazas, evalúe y analice vulnerabilidad.",
        "puntaje_maximo": Decimal("5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Hacer",
        "codigo": "III-5.1.2",
        "nombre": "Brigada de prevención conformada, capacitada y dotada",
        "descripcion": "Conformar, capacitar y dotar la brigada de prevención y respuesta ante emergencias.",
        "puntaje_maximo": Decimal("5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Verificar",
        "codigo": "III-6.1.1",
        "nombre": "Indicadores del SG-SST",
        "descripcion": "Definir indicadores que evalúen el SG-SST conforme los mínimos de la Resolución.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Verificar",
        "codigo": "III-6.1.2",
        "nombre": "Auditoría anual",
        "descripcion": "Realizar auditoría anual planificada con participación del COPASST.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Verificar",
        "codigo": "III-6.1.3",
        "nombre": "Revisión anual por la alta dirección",
        "descripcion": "Revisar mínimo una vez al año los resultados y alcance de la auditoría del SG-SST.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Verificar",
        "codigo": "III-6.1.4",
        "nombre": "Planificación auditoría con el COPASST",
        "descripcion": "Planificar y comunicar resultados de la auditoría al COPASST y al responsable del SG-SST.",
        "puntaje_maximo": Decimal("1.25"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Actuar",
        "codigo": "III-7.1.1",
        "nombre": "Acciones preventivas y correctivas con base en resultados del SG-SST",
        "descripcion": "Definir e implementar acciones preventivas y/o correctivas según resultados de supervisión.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Actuar",
        "codigo": "III-7.1.2",
        "nombre": "Acciones de mejora conforme a revisión de la Alta Dirección",
        "descripcion": "Implementar acciones cuando se detecte que medidas de control son inadecuadas.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Actuar",
        "codigo": "III-7.1.3",
        "nombre": "Acciones de mejora con base en investigaciones de accidentes y enfermedades laborales",
        "descripcion": "Definir e implementar acciones correctivas con base en investigaciones de accidentes.",
        "puntaje_maximo": Decimal("2.5"),
    },
    {
        "capitulo": "III",
        "ciclo_phva": "Actuar",
        "codigo": "III-7.1.4",
        "nombre": "Plan de mejoramiento e implementación de medidas correctivas solicitadas por autoridades y ARL",
        "descripcion": "Implementar medidas correctivas producto de requerimientos de autoridades y ARL.",
        "puntaje_maximo": Decimal("2.5"),
    },
]


class Command(BaseCommand):
    help = "Poblar estándares de la Resolución 0312 de 2019 (Capítulos I, II y III)"

    def handle(self, *args, **options):
        self.stdout.write("Poblando estándares de la Resolución 0312 de 2019...")

        creados = 0
        actualizados = 0

        for data in ESTANDARES_DATA:
            estandar, created = Estandar.objects.update_or_create(
                codigo=data["codigo"],
                defaults={
                    "capitulo": data["capitulo"],
                    "ciclo_phva": data["ciclo_phva"],
                    "nombre": data["nombre"],
                    "descripcion": data["descripcion"],
                    "puntaje_maximo": data["puntaje_maximo"],
                },
            )
            if created:
                creados += 1
            else:
                actualizados += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"[OK] Estandares poblados correctamente. Creados: {creados}, Actualizados: {actualizados}. Total: {Estandar.objects.count()}"
            )
        )
