# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estandares', '0001_initial'),
        ('evidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('auditoria', 'Auditoría'), ('revision_alta_direccion', 'Revisión por la alta dirección'), ('ejecutivo', 'Ejecutivo')], max_length=30)),
                ('contenido_json', models.JSONField(blank=True, null=True)),
                ('fecha_elaboracion', models.DateTimeField(auto_now_add=True)),
                ('firmado_responsable', models.BooleanField(default=False)),
                ('firmado_direccion', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to='evidencias.archivo')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='estandares.evaluacion')),
            ],
            options={
                'db_table': 'informes',
            },
        ),
    ]
