# Generated by Django 6.1 on 2026-09-27 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='firma_direccion_data',
            field=models.TextField(blank=True, help_text='Imagen base64 de la firma gráfica', null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='firma_direccion_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='firma_direccion_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_firmados_direccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe',
            name='firma_responsable_data',
            field=models.TextField(blank=True, help_text='Imagen base64 de la firma gráfica', null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='firma_responsable_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='firma_responsable_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_firmados_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe',
            name='hash_documento',
            field=models.CharField(blank=True, help_text='Hash SHA-256 del documento firmado', max_length=64, null=True),
        ),
    ]
