# Generated by Django 6.1 on 2026-08-21 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('empresas', '0002_empresa_ciiu_768_metadata_empresa_ciiu_768_principal_and_more'),
        ('organizacion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brecha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, help_text='Código auto-generado: BR-YYYY-NNNNNN', max_length=20, unique=True)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('clasificacion', models.CharField(choices=[('incumplimiento', 'Incumplimiento'), ('restriccion', 'Restricción'), ('observacion', 'Observación'), ('hallazgo', 'Hallazgo'), ('oportunidad_mejora', 'Oportunidad de mejora'), ('no_conformidad', 'No conformidad'), ('riesgo_emergente', 'Riesgo emergente')], max_length=30)),
                ('estado', models.CharField(choices=[('detectada', 'Detectada'), ('en_tratamiento', 'En tratamiento'), ('controlada', 'Controlada'), ('subsanada', 'Subsanada'), ('cerrada', 'Cerrada')], default='detectada', max_length=20)),
                ('detectado_por', models.CharField(help_text="Usuario o 'sistema' + nombre del motor (ej. 'Sistema (MICHC)')", max_length=255)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_automatica', models.TextField(blank=True, help_text='Generada por IA — qué ocurrió / dónde / qué requisito afecta')),
                ('interpretacion_ia', models.TextField(blank=True)),
                ('recomendacion_automatica', models.TextField(blank=True)),
                ('descripcion_complementaria', models.TextField(blank=True, help_text='Editable por la empresa — complementa la descripción automática')),
                ('nivel_atencion', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brechas', to='empresas.empresa')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brechas', to='organizacion.proceso')),
                ('responsable_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brechas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brechas', to='organizacion.sede')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brechas', to='capacitaciones.trabajador')),
            ],
            options={
                'db_table': 'brechas',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='BrechaAccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('vencida', 'Vencida')], default='programada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='hbseo.brecha')),
            ],
            options={
                'db_table': 'brecha_acciones',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='BrechaEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('deteccion', 'Detección'), ('descripcion_registrada', 'Descripción registrada'), ('medida_control', 'Medida de control'), ('cambio_estado', 'Cambio de estado'), ('proxima_accion', 'Próxima acción'), ('origen_vinculado', 'Origen vinculado')], max_length=30)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='hbseo.brecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_brecha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brecha_eventos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrechaOrigen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modulo_origen', models.CharField(choices=[('gestion_humana', 'Gestión Humana'), ('michc', 'MICHC'), ('formacion', 'Formación y Desarrollo'), ('sst', 'SST'), ('pesv', 'PESV'), ('ambiental', 'Gestión Ambiental'), ('auditorias', 'Auditorías'), ('indicadores', 'Indicadores')], max_length=30)),
                ('object_id', models.CharField(max_length=255)),
                ('es_origen_principal', models.BooleanField(default=False, help_text='Cuál de los orígenes fue el que disparó la creación de la brecha')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del aporte de este origen a la brecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='hbseo.brecha')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'brecha_origenes',
            },
        ),
        migrations.AddIndex(
            model_name='brecha',
            index=models.Index(fields=['empresa', 'estado'], name='brechas_empresa_e9c6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='brecha',
            index=models.Index(fields=['empresa', 'clasificacion'], name='brechas_empresa_0dcbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='brecha',
            index=models.Index(fields=['trabajador', 'estado'], name='brechas_trabaja_199842_idx'),
        ),
        migrations.AddIndex(
            model_name='brechaorigen',
            index=models.Index(fields=['content_type', 'object_id'], name='brecha_orig_content_e49b07_idx'),
        ),
    ]
