# Generated by Django 5.1.4 on 2026-07-04 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de inicio de sesión fallido'), ('REGISTRO', 'Registro de usuario'), ('ACTIVACION_CUENTA', 'Activación de cuenta'), ('CAMBIO_PASSWORD', 'Cambio de contraseña'), ('RESET_PASSWORD', 'Recuperación de contraseña'), ('CREACION', 'Creación de registro'), ('ACTUALIZACION', 'Actualización de registro'), ('ELIMINACION', 'Eliminación de registro'), ('ACCION_ADMIN', 'Acción administrativa')], max_length=30)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100)),
                ('registro_id', models.CharField(blank=True, max_length=100)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'created_at'], name='audit_logs_usuario_38bf18_idx'), models.Index(fields=['accion', 'created_at'], name='audit_logs_accion_63db78_idx')],
            },
        ),
    ]
