# Generated by Django 6.1 on 2026-08-21 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0004_trabajador_estado_contractual_and_more'),
        ('evidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenMedicoOcupacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso (Pre-empleo)'), ('periodico', 'Periódico'), ('egreso', 'Egreso (Retiro)'), ('post_incapacidad', 'Post-incapacidad / Reintegro'), ('cambio_cargo', 'Cambio de cargo')], max_length=30)),
                ('fecha_examen', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('concepto_aptitud', models.CharField(choices=[('apto', 'Apto para el cargo'), ('apto_con_restricciones', 'Apto con restricciones'), ('no_apto', 'No apto para el cargo'), ('aplazado', 'Evaluación aplazada / Pendiente paraclínicos')], default='apto', max_length=30)),
                ('presenta_restricciones', models.BooleanField(default=False)),
                ('descripcion_restricciones', models.TextField(blank=True, null=True)),
                ('medico_evaluador', models.CharField(blank=True, max_length=200, null=True)),
                ('licencia_so_medico', models.CharField(blank=True, help_text='Licencia en Salud Ocupacional del médico', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_medicos', to='evidencias.archivo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_medicos', to='capacitaciones.trabajador')),
            ],
            options={
                'db_table': 'examenes_medicos_ocupacionales',
                'ordering': ['-fecha_examen'],
                'indexes': [models.Index(fields=['trabajador', 'fecha_examen'], name='examenes_me_trabaja_23d69a_idx'), models.Index(fields=['fecha_vencimiento'], name='examenes_me_fecha_v_00aa9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenciaConduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(help_text='Ej: A1, A2, B1, B2, C1, C2, C3', max_length=10)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('presenta_restricciones', models.BooleanField(default=False)),
                ('descripcion_restricciones', models.TextField(blank=True, help_text='Ej: Uso de lentes, vehículo adaptado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_conduccion', to='evidencias.archivo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias_conduccion', to='capacitaciones.trabajador')),
            ],
            options={
                'db_table': 'licencias_conduccion',
                'ordering': ['-fecha_vencimiento'],
                'indexes': [models.Index(fields=['trabajador', 'fecha_vencimiento'], name='licencias_c_trabaja_e1725a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NovedadLaboral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('incapacidad', 'Incapacidad médica'), ('suspension', 'Suspensión'), ('periodo_prueba', 'Periodo de prueba'), ('reintegro', 'Reintegro')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias', models.PositiveIntegerField(blank=True, help_text='Duración en días calendario', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo_soporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_laborales', to='evidencias.archivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_creadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_laborales', to='capacitaciones.trabajador')),
            ],
            options={
                'db_table': 'novedades_laborales',
                'ordering': ['-fecha_inicio', '-created_at'],
                'indexes': [models.Index(fields=['trabajador', 'fecha_inicio', 'fecha_fin'], name='novedades_l_trabaja_0ba64f_idx'), models.Index(fields=['tipo', 'fecha_inicio'], name='novedades_l_tipo_432e5a_idx')],
            },
        ),
    ]
