# Generated by Django 6.1 on 2026-08-22 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0004_trabajador_estado_contractual_and_more'),
        ('perfilcargo', '0003_perfilcargo_fase1_extendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionHabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('semaforo', models.CharField(choices=[('verde', 'Verde (Cumplimiento Total ≥100%)'), ('amarillo', 'Amarillo (Cumplimiento Parcial ≥80%)'), ('rojo', 'Rojo (Incumplimiento Crítico <80%)')], default='rojo', max_length=20)),
                ('estado_habilitacion', models.CharField(choices=[('habilitado', 'Habilitado'), ('restringido', 'Restringido (Con observaciones)'), ('pendiente_documental', 'Pendiente Documental'), ('no_apto', 'No Apto')], default='pendiente_documental', max_length=30)),
                ('compatibilidad', models.CharField(choices=[('compatible', 'Compatible'), ('compatible_con_restricciones', 'Compatible con Restricciones'), ('incompatible_temporal', 'Incompatible Temporal')], default='compatible', max_length=40)),
                ('nivel_atencion', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=20)),
                ('interpretacion_ia', models.TextField(blank=True, null=True)),
                ('recomendacion_ia', models.TextField(blank=True, null=True)),
                ('contexto_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('calculado_at', models.DateTimeField(auto_now=True)),
                ('perfil_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_habilitacion', to='perfilcargo.perfilcargo')),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_habilitacion', to='capacitaciones.trabajador')),
            ],
            options={
                'db_table': 'evaluaciones_habilitacion_michc',
                'ordering': ['porcentaje_cumplimiento', '-calculado_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCumplimientoRequisito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_requisito', models.CharField(choices=[('educacion', 'Educación / Nivel Académico'), ('experiencia', 'Experiencia Laboral'), ('formacion', 'Formación / Cursos Obligatorios'), ('certificacion', 'Certificaciones Específicas'), ('licencia', 'Licencia de Conducción / Profesional'), ('aptitud_medica', 'Aptitud Médica / Exámenes'), ('restriccion_medica', 'Evaluación de Restricciones Médicas'), ('competencia', 'Competencias del Cargo'), ('afiliacion', 'Afiliaciones a Seguridad Social')], max_length=30)),
                ('requisito_descripcion', models.CharField(max_length=300)),
                ('cumple', models.CharField(choices=[('si', 'Cumple Totalmente'), ('parcial', 'Cumple Parcialmente'), ('no', 'No Cumple'), ('no_aplica', 'No Aplica')], default='no', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('evidencia_id', models.CharField(blank=True, help_text='ID del archivo/registro que soporta el cumplimiento', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluacion_habilitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_requisitos', to='michc.evaluacionhabilitacion')),
            ],
            options={
                'db_table': 'detalles_cumplimiento_michc',
                'ordering': ['tipo_requisito', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluacionhabilitacion',
            index=models.Index(fields=['trabajador', 'semaforo'], name='evaluacione_trabaja_29b189_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionhabilitacion',
            index=models.Index(fields=['perfil_cargo', 'estado_habilitacion'], name='evaluacione_perfil__b51a73_idx'),
        ),
    ]
