# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estandar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capitulo', models.CharField(max_length=10)),
                ('ciclo_phva', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obligatorio', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estandares',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('capitulo', models.CharField(max_length=10)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completada', 'Completada')], default='en_progreso', max_length=20)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='empresas.empresa')),
            ],
            options={
                'db_table': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('parcial', 'Parcial'), ('no_aplica', 'No aplica')], max_length=20)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estandar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='estandares.estandar')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='estandares.evaluacion')),
            ],
            options={
                'db_table': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='Apelacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('respuesta_auditor', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apelaciones', to=settings.AUTH_USER_MODEL)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apelaciones', to='estandares.respuesta')),
            ],
            options={
                'db_table': 'apelaciones',
            },
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'anio'), name='uq_evaluacion_empresa_anio'),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'estandar'), name='uq_respuesta_evaluacion_estandar'),
        ),
    ]
