# Generated by Django 6.1 on 2026-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apelacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
