# Generated by Django 5.1.4 on 2026-07-06 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioActividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('capacitacion', 'Capacitación'), ('auditoria', 'Auditoría'), ('vencimiento', 'Vencimiento'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='empresas.empresa')),
            ],
            options={
                'db_table': 'calendario_actividades',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('accidente', 'Accidente'), ('incidente', 'Incidente'), ('enfermedad_laboral', 'Enfermedad laboral')], max_length=30)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('estado_investigacion', models.CharField(default='pendiente', max_length=30)),
                ('dias_incapacidad', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='empresas.empresa')),
            ],
            options={
                'db_table': 'incidentes',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('recordatorio', 'Recordatorio'), ('informativa', 'Informativa')], max_length=20)),
                ('nivel', models.CharField(choices=[('normal', 'Normal'), ('importante', 'Importante'), ('critico', 'Crítico')], default='normal', max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('enviado_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='calendario.calendarioactividad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
