# Generated by Django 5.1.4 on 2026-07-04 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRiesgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('LOGIN_NUEVO_DISPOSITIVO', 'Login desde dispositivo nuevo'), ('MULTIPLES_FALLOS', 'Múltiples intentos fallidos'), ('CUENTA_BLOQUEADA', 'Cuenta bloqueada temporalmente'), ('IP_BLOQUEADA', 'IP bloqueada temporalmente'), ('RATE_LIMIT_EXCEDIDO', 'Límite de peticiones excedido'), ('OTP_FALLIDO_REPETIDO', 'Múltiples códigos OTP incorrectos')], max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_riesgo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eventos_riesgo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoConocido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('navegador', models.CharField(blank=True, max_length=100)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispositivos_conocidos',
                'unique_together': {('usuario', 'fingerprint')},
            },
        ),
    ]
