# Generated by Django 6.1 on 2026-08-21 02:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_ciiu_768_metadata_empresa_ciiu_768_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAlerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único de la regla, ej. VENC_CONTRATO_60D', max_length=60)),
                ('nombre', models.CharField(max_length=200)),
                ('modelo_origen', models.CharField(choices=[('Trabajador', 'Trabajador (Contratos / Periodo de prueba)'), ('ExamenMedicoOcupacional', 'Examen Médico Ocupacional'), ('LicenciaConduccion', 'Licencia de Conducción'), ('AfiliacionTrabajador', 'Afiliación a Seguridad Social')], max_length=50)),
                ('campo_fecha', models.CharField(help_text='Nombre del campo de fecha en el modelo, ej: fecha_fin_contrato', max_length=100)),
                ('dias_anticipacion', models.IntegerField(help_text='Días de anticipación antes de la fecha (0 = vence hoy / vencido)')),
                ('nivel_criticidad', models.CharField(choices=[('normal', 'Normal'), ('importante', 'Importante'), ('critico', 'Crítico')], default='normal', max_length=20)),
                ('mensaje_template', models.TextField(help_text='Plantilla de mensaje. Placeholders: {trabajador}, {documento}, {fecha}, {dias}, {cargo}, {tipo}')),
                ('roles_destinatarios', models.JSONField(default=list, help_text="Lista de roles a notificar, ej: ['RESPONSABLE', 'ALTA_DIRECCION']")),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Null para regla global del sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_alerta', to='empresas.empresa')),
            ],
            options={
                'db_table': 'reglas_alerta',
                'ordering': ['modelo_origen', 'dias_anticipacion'],
            },
        ),
    ]
