# Generated by Django 6.1 on 2026-09-18 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_ciiu_768_metadata_empresa_ciiu_768_principal_and_more'),
        ('evidencias', '0001_initial'),
        ('organizacion', '0002_initial'),
        ('perfilcargo', '0003_perfilcargo_fase1_extendido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso por Protección Temporal'), ('OTRO', 'Otro')], default='CC', max_length=20)),
                ('documento', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('fuente_detalle', models.CharField(blank=True, default='', max_length=255)),
                ('autoriza_tratamiento_datos', models.BooleanField(default=False, help_text='Consentimiento de Habeas Data según Ley 1581 de 2012')),
                ('fecha_autorizacion_datos', models.DateTimeField(blank=True, null=True)),
                ('etiquetas', models.JSONField(blank=True, default=list, help_text='Etiquetas de habilidades/búsqueda')),
                ('notas_internas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='empresas.empresa')),
            ],
            options={
                'db_table': 'reclutamiento_candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('hoja_de_vida', 'Hoja de Vida'), ('certificacion_laboral', 'Certificación Laboral'), ('certificacion_academica', 'Certificación Académica'), ('licencia_conduccion', 'Licencia de Conducción'), ('licencia_sst', 'Licencia SST'), ('certificacion_alturas', 'Certificación Trabajo en Alturas'), ('cedula', 'Documento de Identidad'), ('otro', 'Otro')], default='hoja_de_vida', max_length=50)),
                ('nombre_descriptivo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_candidato', to='evidencias.archivo')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='reclutamiento.candidato')),
            ],
            options={
                'db_table': 'reclutamiento_candidatos_documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuenteReclutamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('es_sistema', models.BooleanField(default=False, help_text='Valores semilla por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_reclutamiento', to='empresas.empresa')),
            ],
            options={
                'db_table': 'reclutamiento_fuentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='fuente_reclutamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos', to='reclutamiento.fuentereclutamiento'),
        ),
        migrations.CreateModel(
            name='PerfilCandidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo_profesional', models.CharField(blank=True, default='', max_length=255)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('bachillerato', 'Bachillerato / Secundaria'), ('tecnico', 'Técnico Laboral / Profesional'), ('tecnologo', 'Tecnólogo'), ('universitario', 'Profesional / Universitario'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('otro', 'Otro')], default='', max_length=50)),
                ('resumen_profesional', models.TextField(blank=True, default='')),
                ('anios_experiencia', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('experiencia_laboral', models.JSONField(blank=True, default=list, help_text='Lista de objetos: {empresa, cargo, fecha_inicio, fecha_fin, actual, funciones}')),
                ('formacion_academica', models.JSONField(blank=True, default=list, help_text='Lista de objetos: {institucion, titulo, nivel, anio_graduacion, en_curso}')),
                ('certificaciones', models.JSONField(blank=True, default=list, help_text='Lista de certificaciones y licencias (p. ej. Alturas, SST, CONTE)')),
                ('competencias', models.JSONField(blank=True, default=list, help_text='Lista de competencias técnicas y blandas')),
                ('aspiracion_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponibilidad_viaje', models.BooleanField(default=False)),
                ('disponibilidad_traslado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='reclutamiento.candidato')),
            ],
            options={
                'db_table': 'reclutamiento_perfiles_candidato',
            },
        ),
        migrations.CreateModel(
            name='TokenAccesoCandidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('codigo_otp', models.CharField(blank=True, default='', max_length=6)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acceso', to='reclutamiento.candidato')),
            ],
            options={
                'db_table': 'reclutamiento_tokens_candidato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('descripcion_publica', models.TextField(blank=True, default='')),
                ('numero_cupos', models.PositiveIntegerField(default=1)),
                ('numero_seleccionados', models.PositiveIntegerField(default=0)),
                ('tipo_contrato', models.CharField(blank=True, default='', max_length=100)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=30)),
                ('rango_salarial_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rango_salarial_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mostrar_salario_publico', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta / Publicada'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada'), ('cubierta', 'Cubierta')], default='borrador', max_length=30)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('fecha_cierre_real', models.DateField(blank=True, null=True)),
                ('publicada_en_portal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='empresas.empresa')),
                ('perfil_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='perfilcargo.perfilcargo')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes', to='organizacion.sede')),
            ],
            options={
                'db_table': 'reclutamiento_vacantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoSeleccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('requiere_entrevista', models.BooleanField(default=True, help_text='RN-R03: Etapa de entrevista obligatoria para este proceso')),
                ('requiere_evaluacion', models.BooleanField(default=True, help_text='RN-R03: Etapa de evaluación técnica/psicotécnica obligatoria')),
                ('requiere_validacion_documental', models.BooleanField(default=True, help_text='RN-R03: Etapa de validación documental y de referencias obligatoria')),
                ('requisitos_obligatorios', models.JSONField(blank=True, default=list, help_text='Requisitos excluyentes tomados del PerfilCargo o definidos en la convocatoria')),
                ('requisitos_deseables', models.JSONField(blank=True, default=list, help_text='Requisitos adicionales valorables')),
                ('criterios_evaluacion', models.JSONField(blank=True, default=dict, help_text='Pesos o escalas de calificación por etapa')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_pausa', 'En Pausa'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_seleccion', to='empresas.empresa')),
                ('responsable_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_seleccion_liderados', to=settings.AUTH_USER_MODEL)),
                ('vacante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceso_seleccion', to='reclutamiento.vacante')),
            ],
            options={
                'db_table': 'reclutamiento_procesos_seleccion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fuentereclutamiento',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_fuente_nombre_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'tipo_documento', 'documento'), name='unique_candidato_documento_empresa'),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'email'), name='unique_candidato_email_empresa'),
        ),
    ]
