# Generated by Django 6.1 on 2026-09-18 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_ciiu_768_metadata_empresa_ciiu_768_principal_and_more'),
        ('reclutamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('postulado', 'Postulado'), ('en_revision', 'En Revisión'), ('preseleccionado', 'Preseleccionado'), ('en_entrevista', 'En Entrevista'), ('en_evaluacion', 'En Evaluación'), ('en_validacion', 'En Validación Documental'), ('seleccionado', 'Seleccionado'), ('no_seleccionado', 'No Seleccionado'), ('retiro_candidatura', 'Retiro de Candidatura'), ('no_continuo', 'No Continuó en Proceso')], db_index=True, default='postulado', max_length=30)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_general', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación global ponderada sobre 100', max_digits=5, null=True)),
                ('calificacion_requisitos', models.JSONField(blank=True, default=dict, help_text='Cumplimiento detallado de requisitos obligatorios y deseables')),
                ('etapas_completadas', models.JSONField(blank=True, default=list, help_text='Lista de etapas superadas (entrevista, evaluacion, validacion_documental)')),
                ('motivo_cierre', models.TextField(blank=True, default='', help_text='RN-R04: Motivo obligatorio para estados de cierre')),
                ('es_excepcion', models.BooleanField(default=False, help_text='RN-R09: Si la transición actual fue autorizada por excepción')),
                ('justificacion_excepcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='reclutamiento.candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empresas.empresa')),
                ('proceso_seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='reclutamiento.procesoseleccion')),
            ],
            options={
                'db_table': 'reclutamiento_postulaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostulacionEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('postulacion_registrada', 'Postulación Registrada'), ('cambio_estado', 'Cambio de Estado'), ('evaluacion_requisitos', 'Evaluación de Requisitos'), ('entrevista_registrada', 'Entrevista Registrada'), ('prueba_registrada', 'Prueba / Evaluación Registrada'), ('validacion_registrada', 'Validación Documental Registrada'), ('decision_seleccion', 'Decisión Final de Selección'), ('cierre_postulacion', 'Cierre de Postulación'), ('reapertura_excepcional', 'Reapertura Excepcional')], default='cambio_estado', max_length=40)),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('es_excepcion', models.BooleanField(default=False)),
                ('justificacion_excepcion', models.TextField(blank=True, default='')),
                ('datos_capturados', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='reclutamiento.postulacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_postulacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclutamiento_postulacion_eventos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='postulacion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('proceso_seleccion', 'candidato'), name='unique_postulacion_candidato_proceso'),
        ),
    ]
