# Generated by Django 6.1 on 2026-09-18 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_ciiu_768_metadata_empresa_ciiu_768_principal_and_more'),
        ('evidencias', '0001_initial'),
        ('reclutamiento', '0002_postulacion_postulacionevento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_entrevista', models.CharField(choices=[('inicial_rh', 'Inicial / Recursos Humanos'), ('tecnica', 'Técnica / Competencias'), ('jefe_inmediato', 'Jefe Inmediato'), ('gerencial', 'Gerencial / Alta Dirección'), ('otra', 'Otra')], default='inicial_rh', max_length=30)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual / Videollamada'), ('telefonica', 'Telefónica')], default='virtual', max_length=20)),
                ('fecha_programada', models.DateTimeField()),
                ('enlace_reunion', models.URLField(blank=True, default='')),
                ('lugar', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada'), ('no_asistio', 'No Asistió')], default='programada', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Puntuación obtenida sobre 100', max_digits=5, null=True)),
                ('concepto', models.CharField(choices=[('favorable', 'Favorable / Aprobado'), ('desfavorable', 'Desfavorable / No Aprobado'), ('con_reservas', 'Favorable con Reservas'), ('pendiente', 'Pendiente de Concepto')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('aspectos_evaluados', models.JSONField(blank=True, default=dict, help_text='Evaluación por competencias: {liderazgo: 4, comunicacion: 5, etc.}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas_candidatos', to='empresas.empresa')),
                ('entrevistador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='reclutamiento.postulacion')),
            ],
            options={
                'db_table': 'reclutamiento_entrevistas',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evaluacion', models.CharField(choices=[('tecnica', 'Prueba Técnica / Conocimientos'), ('psicotecnica', 'Prueba Psicotécnica'), ('conocimientos_sst', 'Evaluación Específica SST / GTC 45'), ('operativa_practica', 'Prueba Práctica / Operativa'), ('medica_preingreso', 'Concepto Médico Preingreso'), ('otra', 'Otra Prueba')], default='tecnica', max_length=30)),
                ('nombre_prueba', models.CharField(max_length=255)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('porcentaje_aprobacion', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente / Asignada'), ('en_curso', 'En Curso'), ('aprobada', 'Aprobada'), ('no_aprobada', 'No Aprobada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('concepto', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo_informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_informe', to='evidencias.archivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_candidatos', to='empresas.empresa')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='reclutamiento.postulacion')),
            ],
            options={
                'db_table': 'reclutamiento_evaluaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionDocumental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_verificacion', models.CharField(choices=[('referencia_laboral', 'Referencia Laboral'), ('referencia_personal', 'Referencia Personal'), ('titulo_academico', 'Título Académico'), ('licencia_conduccion', 'Licencia de Conducción (RUNT)'), ('licencia_sst', 'Licencia SST (Secretaría de Salud)'), ('certificacion_alturas', 'Certificación Alturas (MinTrabajo)'), ('antecedentes', 'Antecedentes Judiciales / Procuraduría / Contraloría'), ('otro', 'Otro Documento')], default='referencia_laboral', max_length=40)),
                ('entidad_o_contacto', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado_conforme', 'Verificado Conforme / Válido'), ('verificado_con_inconsistencias', 'Con Inconsistencias'), ('no_pudo_verificarse', 'No Pudo Verificarse')], default='pendiente', max_length=35)),
                ('detalles_verificacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_documentales_candidatos', to='empresas.empresa')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_documentales', to='reclutamiento.postulacion')),
                ('soporte_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_soporte', to='evidencias.archivo')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclutamiento_validaciones_documentales',
                'ordering': ['-created_at'],
            },
        ),
    ]
