# Generated by Django 6.1 on 2026-09-27 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0003_entrevista_evaluacion_validaciondocumental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRolProceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('seleccionador', 'Seleccionador / RH'), ('entrevistador', 'Entrevistador'), ('evaluador', 'Evaluador'), ('admin', 'Administrador de Selección')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proceso_seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='reclutamiento.procesoseleccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_reclutamiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclutamiento_asignaciones_rol',
                'unique_together': {('proceso_seleccion', 'usuario', 'rol')},
            },
        ),
    ]
